Build system updates

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -10,10 +10,6 @@ test -z "$srcdir" && srcdir=.
 
 cd "$srcdir"
 
-FREESTANDING_TOOLCHAIN_COMMIT_HASH=18a5e52483344e117d45738c9afb2b34792cbced
-FREESTANDING_HEADERS_COMMIT_HASH=dd3abd2d7147efc4170dff478d3b7730bed14147
-CC_RUNTIME_COMMIT_HASH=aa5854cebb4a5a561f35252cdda741919fc9c3f6
-
 AUXFILES="install-sh"
 
 clone_repo_commit() {
@@ -35,12 +31,55 @@ clone_repo_commit() {
     fi
 }
 
-if ! test -f version; then
-    clone_repo_commit https://github.com/osdev0/freestanding-toolchain.git build-aux/freestanding-toolchain $FREESTANDING_TOOLCHAIN_COMMIT_HASH
-    clone_repo_commit https://github.com/osdev0/freestanding-headers.git freestanding-headers $FREESTANDING_HEADERS_COMMIT_HASH
-    clone_repo_commit https://github.com/osdev0/cc-runtime.git src/cc-runtime $CC_RUNTIME_COMMIT_HASH
+download_by_hash() {
+    DOWNLOAD_COMMAND="curl -Lo"
+    if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
+        DOWNLOAD_COMMAND="wget -O"
+        if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
+            echo "error: Neither curl nor wget found"
+            exit 1
+        fi
+    fi
+    SHA256_COMMAND="sha256sum"
+    if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
+        SHA256_COMMAND="sha256"
+        if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
+            echo "error: Cannot find sha256(sum) command"
+            exit 1
+        fi
+    fi
+    if ! test -f $2 || ! $SHA256_COMMAND $2 | grep $3 >/dev/null 2>&1; then
+        rm -f $2
+        mkdir -p $2 && rm -rf $2
+        $DOWNLOAD_COMMAND $2 $1
+        if ! $SHA256_COMMAND $2 | grep $3 >/dev/null 2>&1; then
+            echo "error: Cannot download file '$2' by hash"
+            exit 1
+        fi
+    fi
+}
 
-    [ -f src/limine.h ] || curl -Lo src/limine.h https://github.com/limine-bootloader/limine/raw/trunk/limine.h
+if ! test -f version; then
+    clone_repo_commit \
+        https://github.com/osdev0/freestanding-headers.git \
+        freestanding-headers \
+        dd3abd2d7147efc4170dff478d3b7730bed14147
+
+    clone_repo_commit \
+        https://github.com/osdev0/cc-runtime.git \
+        src/cc-runtime \
+        aa5854cebb4a5a561f35252cdda741919fc9c3f6
+
+    download_by_hash \
+        https://github.com/osdev0/freestanding-toolchain/raw/18a5e52483344e117d45738c9afb2b34792cbced/freestanding-toolchain \
+        build-aux/freestanding-toolchain \
+        b5b66c4e94d463116e549b10e78fb96cdb97530cc165f9b5babe31a97a78e90c
+    chmod +x build-aux/freestanding-toolchain
+
+    download_by_hash \
+        https://github.com/limine-bootloader/limine/raw/9db882c736d4fa84fa313f235ac92b758a730210/limine.h \
+        src/limine.h \
+        ee166c7859b31879ee7f7d4c1556c3e0ec13866922256613288bcc416c82fcd8
 fi
 
 for auxfile in $AUXFILES; do
